// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwangqyzvegipainxlxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3YW5ncXl6dmVnaXBhaW54bHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDE2OTcsImV4cCI6MjA2MjYxNzY5N30.LblhMFo9avHsOyFkFhf4kJVovnyJnP16zD-9lCPb8Fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);